Name = input("What is your name? : ")
Food = input("What is your favorite food? : ")
Music = input ("What is your favorite music?")
Live = input ("Where do you live?")
print()
print("You are")
print(Name)
print("You are probably hunrgy for")
print(Food)
print("and you definetly love listening to")
print(Music)
print("and I bet living in")
print(Live)
print("is amazing!")